title: Me, Myself and Technology Projects
description: My Interpretation of Technology
author: Joe Mendes
github: https://github.com/JoeGMendes
about: I am an Embedded Developer. 
disqus_shortname: joegmendes-technology-and-projects
google_analytics: UA-87332602-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/jgmendes"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/joegmendes"
    - icon: fa-bitbucket
      link: "https://bitbucket.org/jgmendes"
    - icon: fa-github
      link: "https://github.com/joegmendes"

share:
  twitter_username: jgmendes

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/

url: "https://JoeGmendes.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
